import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/about'
import Projects from '../components/projects'
import Tagline from '../components/tagline'
import Contact from '../components/contact'
import Link from 'next/link';
import { useRouter } from 'next/router';
import { projectdataEN } from '../public/projectsdata'
import { projectdataFR } from '../public/projectsdataFR'
import { projectdataES } from '../public/projectsdataES'

const Home: NextPage = () => {
  const { locale, locales, defaultLocale, asPath } = useRouter();
  const [mainData, setMainData] = useState(projectdataEN)

  useEffect(() => {
    switch (locale) {
      case 'es-ES':
        setMainData(projectdataES)
        break
      case 'fr-FR':
        setMainData(projectdataFR)
        break
      case 'en-US':
        setMainData(projectdataEN)
        break
      default:
    }
  },[locale])

  return (
    <>
      <Head>
        <title>Mathias Prost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tagline file={mainData} />
      <About file={mainData} />
      <Projects file={mainData} />
      <Contact file={mainData} />
    </>
  )
}

export default Home
