import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/about'
import Projects from '../components/projects'
import Tagline from '../components/tagline'
import Image from 'next/image'
import Card from '../components/Card'
import Grid from '../components/Grid'
import Contact from '../components/contact'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mathias Prost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tagline />
      <About />
      <Projects />
      <Contact />
    </>
  )
}

export default Home
